// Generated by CoffeeScript 1.10.0
(function() {
    var express = require('express');
    var app = express();
    app.set('views', './app');
    app.set('view engine', 'html');

    app.use(express.static(__dirname + '/app'));

    var port = Number(process.env.PORT || 8000);

    app.listen(port, function () {
        console.log('Example app listening on port 3000!');
    });
}).call(this);