// Generated by CoffeeScript 1.10.0
(function() {
    var express = require('express');
    var app = express();
    app.set('views', './dist');
    app.set('view engine', 'html');

    app.use(express.static(__dirname + '/dist'));

    var port = Number(process.env.PORT || 8000);

    app.listen(port, function () {
        console.log('ux-facebook-clone app listening on port '+port);
    });
}).call(this);

